using Extensions;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace GTE
{
    public static class Language
    {
        private static readonly ImmutableDictionary<string, string> m_codes;

        static Language()
        {
            // Retrieved language names and codes from https://gist.github.com/JT5D/a2fdfefa80124a06f5a9/8d448569000ebe6752c7aaac91054a6af8f31c5b
            // Most entries are untested and are likely invalid.
            m_codes = ImmutableDictionary.CreateRange(new KeyValuePair<string, string>[]
            {
                KeyValuePair.Create("afrikaans", "af"),
                KeyValuePair.Create("akan", "ak"),
                KeyValuePair.Create("albanian", "sq"),
                KeyValuePair.Create("amharic", "am"),
                KeyValuePair.Create("arabic", "ar"),
                KeyValuePair.Create("armenian", "hy"),
                KeyValuePair.Create("azerbaijani", "az"),
                KeyValuePair.Create("basque", "eu"),
                KeyValuePair.Create("belarusian", "be"),
                KeyValuePair.Create("bemba", "bem"),
                KeyValuePair.Create("bengali", "bn"),
                KeyValuePair.Create("bihari", "bh"),
                KeyValuePair.Create("bosnian", "bs"),
                KeyValuePair.Create("breton", "br"),
                KeyValuePair.Create("bulgarian", "bg"),
                KeyValuePair.Create("cambodian", "km"),
                KeyValuePair.Create("catalan", "ca"),
                KeyValuePair.Create("cherokee", "chr"),
                KeyValuePair.Create("chichewa", "ny"),
                KeyValuePair.Create("chinese simplified", "zh-CN"),
                KeyValuePair.Create("chinese traditional", "zh-TW"),
                KeyValuePair.Create("corsican", "co"),
                KeyValuePair.Create("croatian", "hr"),
                KeyValuePair.Create("czech", "cs"),
                KeyValuePair.Create("danish", "da"),
                KeyValuePair.Create("dutch", "nl"),
                KeyValuePair.Create("english", "en"),
                KeyValuePair.Create("esperanto", "eo"),
                KeyValuePair.Create("estonian", "et"),
                KeyValuePair.Create("ewe", "ee"),
                KeyValuePair.Create("faroese", "fo"),
                KeyValuePair.Create("filipino", "tl"),
                KeyValuePair.Create("finnish", "fi"),
                KeyValuePair.Create("french", "fr"),
                KeyValuePair.Create("frisian", "fy"),
                KeyValuePair.Create("ga", "gaa"),
                KeyValuePair.Create("galician", "gl"),
                KeyValuePair.Create("georgian", "ka"),
                KeyValuePair.Create("german", "de"),
                KeyValuePair.Create("greek", "el"),
                KeyValuePair.Create("guarani", "gn"),
                KeyValuePair.Create("gujarati", "gu"),
                KeyValuePair.Create("haitian creole", "ht"),
                KeyValuePair.Create("hausa", "ha"),
                KeyValuePair.Create("hawaiian", "haw"),
                KeyValuePair.Create("hebrew", "iw"),
                KeyValuePair.Create("hindi", "hi"),
                KeyValuePair.Create("hungarian", "hu"),
                KeyValuePair.Create("icelandic", "is"),
                KeyValuePair.Create("igbo", "ig"),
                KeyValuePair.Create("indonesian", "id"),
                KeyValuePair.Create("interlingua", "ia"),
                KeyValuePair.Create("irish", "ga"),
                KeyValuePair.Create("italian", "it"),
                KeyValuePair.Create("japanese", "ja"),
                KeyValuePair.Create("javanese", "jw"),
                KeyValuePair.Create("kannada", "kn"),
                KeyValuePair.Create("kazakh", "kk"),
                KeyValuePair.Create("kinyarwanda", "rw"),
                KeyValuePair.Create("kirundi", "rn"),
                KeyValuePair.Create("kongo", "kg"),
                KeyValuePair.Create("korean", "ko"),
                KeyValuePair.Create("krio sierra leone", "kri"),
                KeyValuePair.Create("kurdish", "ku"),
                KeyValuePair.Create("kurdish soranî", "ckb"),
                KeyValuePair.Create("kyrgyz", "ky"),
                KeyValuePair.Create("laothian", "lo"),
                KeyValuePair.Create("latin", "la"),
                KeyValuePair.Create("latvian", "lv"),
                KeyValuePair.Create("lingala", "ln"),
                KeyValuePair.Create("lithuanian", "lt"),
                KeyValuePair.Create("lozi", "loz"),
                KeyValuePair.Create("luganda", "lg"),
                KeyValuePair.Create("luo", "ach"),
                KeyValuePair.Create("macedonian", "mk"),
                KeyValuePair.Create("malagasy", "mg"),
                KeyValuePair.Create("malay", "ms"),
                KeyValuePair.Create("malayalam", "ml"),
                KeyValuePair.Create("maltese", "mt"),
                KeyValuePair.Create("maori", "mi"),
                KeyValuePair.Create("marathi", "mr"),
                KeyValuePair.Create("mauritian creole", "mfe"),
                KeyValuePair.Create("moldavian", "mo"),
                KeyValuePair.Create("mongolian", "mn"),
                KeyValuePair.Create("montenegrin", "sr-ME"),
                KeyValuePair.Create("nepali", "ne"),
                KeyValuePair.Create("nigerian Pidgin", "pcm"),
                KeyValuePair.Create("northern Sotho", "nso"),
                KeyValuePair.Create("norwegian", "no"),
                KeyValuePair.Create("norwegian nynorsk", "nn"),
                KeyValuePair.Create("occitan", "oc"),
                KeyValuePair.Create("oriya", "or"),
                KeyValuePair.Create("oromo", "om"),
                KeyValuePair.Create("pashto", "ps"),
                KeyValuePair.Create("persian", "fa"),
                KeyValuePair.Create("polish", "pl"),
                KeyValuePair.Create("portuguese brazil", "pt-BR"),
                KeyValuePair.Create("portuguese portugal", "pt-PT"),
                KeyValuePair.Create("punjabi", "pa"),
                KeyValuePair.Create("quechua", "qu"),
                KeyValuePair.Create("romanian", "ro"),
                KeyValuePair.Create("romansh", "rm"),
                KeyValuePair.Create("runyakitara", "nyn"),
                KeyValuePair.Create("russian", "ru"),
                KeyValuePair.Create("scots gaelic", "gd"),
                KeyValuePair.Create("serbian", "sr"),
                KeyValuePair.Create("serbo-croatian", "sh"),
                KeyValuePair.Create("sesotho", "st"),
                KeyValuePair.Create("setswana", "tn"),
                KeyValuePair.Create("seychellois creole", "crs"),
                KeyValuePair.Create("shona", "sn"),
                KeyValuePair.Create("sindhi", "sd"),
                KeyValuePair.Create("sinhalese", "si"),
                KeyValuePair.Create("slovak", "sk"),
                KeyValuePair.Create("slovenian", "sl"),
                KeyValuePair.Create("somali", "so"),
                KeyValuePair.Create("spanish", "es"),
                KeyValuePair.Create("spanish latin american", "es-419"),
                KeyValuePair.Create("sundanese", "su"),
                KeyValuePair.Create("swahili", "sw"),
                KeyValuePair.Create("swedish", "sv"),
                KeyValuePair.Create("tajik", "tg"),
                KeyValuePair.Create("tamil", "ta"),
                KeyValuePair.Create("tatar", "tt"),
                KeyValuePair.Create("telugu", "te"),
                KeyValuePair.Create("thai", "th"),
                KeyValuePair.Create("tigrinya", "ti"),
                KeyValuePair.Create("tonga", "to"),
                KeyValuePair.Create("tshiluba", "lua"),
                KeyValuePair.Create("tumbuka", "tum"),
                KeyValuePair.Create("turkish", "tr"),
                KeyValuePair.Create("turkmen", "tk"),
                KeyValuePair.Create("twi", "tw"),
                KeyValuePair.Create("uighur", "ug"),
                KeyValuePair.Create("ukrainian", "uk"),
                KeyValuePair.Create("urdu", "ur"),
                KeyValuePair.Create("uzbek", "uz"),
                KeyValuePair.Create("vietnamese", "vi"),
                KeyValuePair.Create("welsh", "cy"),
                KeyValuePair.Create("wolof", "wo"),
                KeyValuePair.Create("xhosa", "xh"),
                KeyValuePair.Create("yiddish", "yi"),
                KeyValuePair.Create("yoruba", "yo"),
                KeyValuePair.Create("zulu", "zu")
            });
        }

        public static bool TryGetCode(string language, out string code)
        {
            if (m_codes != null && m_codes.TryGetValue(language, out var iso))
            {
                code = iso;
                return true;
            }
            ConsoleColor.Red.WriteLine($"Language: '{language}' is unsupported or was spelt incorrectly");
            code = string.Empty;
            return false;
        }
    }
}